apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: openbao-backup
    namespace: openbao
spec:
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:jF5sf03ZIbh0qQullWeLKrI=,iv:Fj5Ww1eo3gduhooggI9hWu61ZFfdl/JictiSORkp7SA=,tag:ZJXBgmDASpjVhmKl0MgV4Q==,type:str]
          stringData:
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:NDFvMAhadIpwo1MAxkja78nRS7U=,iv:RtWJvHLkl2AKpgX9sClqcpvtk1jDHuXEt5VziJycggE=,tag:nigEeeoDwUXzGWdqja0Y0g==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:8DY6hFdKGgvOQXe9MM4IzotS7gZJll75oelq2ZM8X4yc/pcMeOIN3w==,iv:wfPr5w9eK0SGIDJY2mzpqjW7KJ1ee0mm3w157VXksQg=,tag:cEpOOGvQXuYYQ+jJACSZVA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkTlhacDZ1bWN4SSt4Mkg5
            bSt0T1pOWUgrUlZHY2kzQit3TVNTV3R0VlVBCjRCd1QvS1lIN3NPSlJENCt5c05I
            VEdHcnZ6OXVnVkU2UUxGc0ZWUTFnYzAKLS0tIG8zbS9sVFAwQmJYVGNmU09lTkRE
            T0hNcDZnM0M0ZFdPSE15em5uaXE3MUUKw49FkE5weAJL2Lo7lR4w0hv6w5Ylmfhj
            hKpo0u6zKLk2V/yZoPwO6AGwdQlTFI8Jd2Abu5myqyPr+KXxTuUidg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14vn3sglty83cq3rtkzw0udlh3dak768daneupwxdqafgnewrhcsq9zawc6
    encrypted_suffix: Templates
    lastmodified: "2026-10-03T15:46:11Z"
    mac: ENC[AES256_GCM,data:6E1zotSrPuQ3Ylfac5wMyLkhmWcBPXCR2eaIAJbeLQTzlGGAVQ6p3MapynqAR6mjQe6CEkjFl09Bw2EN/+p2Dml3zH8LdbpNPYhbQUMeNyF7Ol+r7jigZnWCD89sKyuR4ildXHJlZFeui7qlSuXge9aNjmMjLHkXRaMbwW+NVfw=,iv:vURWdGDC+oRjXbx3EZUsktrD83emlRiJeyHuW3N0hWU=,tag:lvxhV5OvhBxSYo6KZ+rt4w==,type:str]
    version: 3.13.3
