apiVersion: v1
kind: Namespace
metadata:
  name: aws-observability
  labels:
    aws-observability: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: customer-service-staging
  labels:
    app.kubernetes.io/part-of: aws-csa
    environment: staging
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-logging
  namespace: aws-observability
data:
  output.conf: |
    [OUTPUT]
        Name cloudwatch_logs
        Match   *
        region {{ .Values.region }}
        log_group_name {{ .Values.fargateLogGroup }}
        log_stream_prefix fargate-
        auto_create_group false
  filters.conf: |
    [FILTER]
        Name parser
        Match *
        Key_name log
        Parser containerd
        Preserve_Key True
        Reserve_Data True
  parsers.conf: |
    [PARSER]
        Name containerd
        Format regex
        Regex ^(?<time>.+) (?<stream>stdout|stderr) (?<logtag>[FP]) (?<log>.*)$
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
---
apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: aws-csa-data-access
  namespace: customer-service-staging
spec:
  podSelector:
    matchLabels:
      aws-csa/data-access: "true"
  securityGroups:
    groupIds:
      - {{ required "workloadSecurityGroupId is required" .Values.workloadSecurityGroupId }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-csa-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repository }}
    targetRevision: {{ .Values.revision }}
    path: helm/customer-service
    helm:
      releaseName: aws-csa
      valueFiles:
        - values.yaml
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: customer-service-staging
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
