{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "customer-support.fullname" . }}-postgres
  labels:
    {{- include "customer-support.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.postgres.password | quote }}
  database-url: {{ printf "postgresql://%s:%s@%s-postgres:5432/%s" .Values.postgres.username .Values.postgres.password (include "customer-support.fullname" .) .Values.postgres.database | quote }}
{{- end }}

