apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-application-redis-access
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: production-redis
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: app
      ports:
        - { protocol: TCP, port: 6379 }
  policyTypes: [Ingress]
