{{- if .Values.backup.enabled }}
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: production-postgres-backup
  namespace: {{ .Values.namespace }}
spec:
  retentionPolicy: {{ .Values.backup.retentionPolicy | quote }}
  configuration:
    destinationPath: {{ printf "s3://%s/%s" .Values.backup.bucket .Values.backup.prefix | quote }}
    endpointURL: {{ .Values.backup.endpointURL | quote }}
    s3Credentials:
      accessKeyId:
        name: {{ .Values.backup.secretName }}
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: {{ .Values.backup.secretName }}
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
  instanceSidecarConfiguration:
    env:
      - { name: AWS_DEFAULT_REGION, value: eu-west-1 }
      - { name: AWS_S3_ADDRESSING_STYLE, value: path }
      - { name: AWS_REQUEST_CHECKSUM_CALCULATION, value: when_required }
      - { name: AWS_RESPONSE_CHECKSUM_VALIDATION, value: when_required }
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: production-postgres-daily
  namespace: {{ .Values.namespace }}
spec:
  schedule: {{ .Values.backup.schedule | quote }}
  backupOwnerReference: self
  cluster:
    name: production-postgres
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
{{- end }}
