apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: operations-alert-email
    namespace: monitoring
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:YfaE91Eyz+ebR3U6eWLXFeW7qB2Vrw==,iv:To4L8sPU4sLP2SRIYUGLC5vC348quBekkOzAK5vY+QI=,tag:d8/dqkV9Ffi6NLKDl3a5NQ==,type:str]
          stringData:
            alertmanager.yaml: ENC[AES256_GCM,data:tXtW6QEaGLWlET4Sf0rKv65J3/3fLEzhEw8+ESbV1nGwaJISoL6bQW77kqS4ogGdhQQbGx1lDJSw/LebrowVhB7s99W9L4e8TZf7aH2SxSwGgX/lFPTpkq5snEdfN4IRXBTQTuGWJajsaFabBVYmTO/J0iPoygIJUbOv3JWXxOMoUAp0YTrIVdnQbIROhnkveSvSl7epj5FPeo5KHHLQLYBo0qeYzbLJD7K4N7YIWALh99Oj8pVt3GmRVG/sR2083FcnisncatCrbe8G0OCTfbI3fsKBcVXuRKwBHU4xbPNJnX2zCT4TzXsW72w7SfXUdrhrg1U616Js535g+eXWyu6+QpnrrVUlc1Ygof6/MQDIw3hRe2yRwpZsV/gVxjwhwaZYODKI3dGOS/9wXSIW2qGI2WBlARN7+8c7nHAZoe5nkZlev+ZfH+GCpZkD+ris9WNiumNfx7emTtX+ST7a1hQotCKui66vRbbNZMz3+87T5QW+SdzVl5WaA1fuFwnN/jsqoliWZ5259cE+VZRXVQNTcxoxgoF3g/ujdOr8voIRYMfYXeYkh6tr+3YJSYFuegcVPj2e2eQ4rofqI0tZKA2aR7SEyTQ60GYtcBAsXc9SrRDrQq1ncRKP7k1O9Y0Vr0JN2GiXYmBR/Gw59nbqB+57rY4pP3SrO+YoPT5bvpd+3l70756+Il7fm7lsjYcvfbiIjYCBdHeDpCo=,iv:H6ehk0bvtOahD3Ed/DHstpwkyscpum4eS6Ie7lBlfB8=,tag:LDEFXj5fu5FxwO9adVb5Ag==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUVJLditxaVhuZVdPRW92
            S3ZLOGEreUQ4MjhxaXYxcmgxd1l5NC9Gd253Ckdqb1U5bHYxb21VYU50ZUQ5eTNl
            MjlkSVBpSmtDVUJVbnZZTUVYem1WdTAKLS0tIDdDWGpzTHVQYktRZVJKWm1HYTR6
            Y01RcmZCeGV1UVFpQk8wanJkSnA3V0kK5Hku8e1BDmsYaxKvv6rXTIOAhnzngS0c
            Yd3E09v2Pep6bCLsJn+ryiEqrT6R4yBo5fpFfnvkHrL8+8iVKm3B2w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14vn3sglty83cq3rtkzw0udlh3dak768daneupwxdqafgnewrhcsq9zawc6
    encrypted_suffix: Templates
    lastmodified: "2026-10-03T15:46:11Z"
    mac: ENC[AES256_GCM,data:kaqf6KDMwLLq409F8rJZux+wH1DVe0gZNeZjnW4xLy8qy4tKo+biGJmL//krRngSA0JQogyim/xvuFmaxGK42H23XcWMaTH0NorVfaDvm6r/xqrsbTtCe9lTiK9vZXMR6OxntiW0fy4DDmkrc7Kq1DxXlTHq6fFdjIpKPiFH+4s=,iv:1hmNLIEbJcq/95CmPA7navCM/2ljFsTdkNvf8YWNcK8=,tag:Sv6zp/3ttxK+rQINJWv5Sw==,type:str]
    version: 3.13.3
