apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: customer-service-production
    namespace: customer-service-production
    annotations:
        argocd.argoproj.io/sync-wave: "15"
spec:
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:tJo7+GkL5bo=,iv:GTc8tfHCx311T5G2pj0rdvbPDrbRKfyU4VSsKW3y8Qo=,tag:buOhXLMJkO8QjNo9eCbciQ==,type:str]
          stringData:
            OPENAI_API_KEY: ENC[AES256_GCM,data:RXZLGF1MENSr59fxmhrJQ4Qu/s9cmDC8zcBb/XeCcbazRR6tlNIBgD9YgfRhfSaZ2PpTItS7r/H50303ScuDuuXBukX4soa5IykyLUFxsWjYZ0aPWKP5CA9dtAWHWnLozVKIQy5bgTYPlfjFddrtMVjH0qPe8KQdsghbsSyxmA9LBFc+SJarE2D07nMiQkcUGTS7wOCKD7LFqUr3OEMos78BH+c=,iv:lRwa/t2orKUsJu7/OfKFrCT97qtfClFWG44hezQ0PmI=,tag:3ZQwa3wtnMi3Trz1VqQADg==,type:str]
            LANGSMITH_API_KEY: ENC[AES256_GCM,data:unHEHhk0nWqa4sXMtZHNlFpjZkYTP5NeJJnv8/vYyY+3mhv9ADLteYCWreRN2QxMH30w,iv:9AJhIWMwHXKtKRHvUf9JNylKHsHDui2pMnF6dyyBs90=,tag:8SAskLNLgUvgloeevUqTQg==,type:str]
            LANGSMITH_WORKSPACE_ID: ENC[AES256_GCM,data:hPULTsqANtWsrIkNECCUcSBlRBjg+lV+FodISpkDthe46cXo,iv:y2nNmLpV7XKy7J5LRZooB/XVvxp9mYBm84laOVucTHE=,tag:U50C7oPjoxxXrF1UEkfUSw==,type:str]
            RESEND_API_KEY: ENC[AES256_GCM,data:TxWL3eLLEFIxUItSwZl9rGhhtOp2a2Jmszu6GrUaGTQkoTDa,iv:FeM4dZyWy7/yOKpjC0a+Nxnk+3TVZVPK1DcrNNA3B4A=,tag:W9aWFC59ypIsU5cwoN419g==,type:str]
            PLATFORM_TAVILY_API_KEY: ENC[AES256_GCM,data:yeFyx4HVJ81zbkbeas9V2n7P7e5LLGrMePhRaX6QO/qX0l2ob1qaAT0xNQ5IzEEN1b/JYIGDxyHTHg==,iv:lFfj0XHNovGvJpuzSauG72O1E7tFv20PRO+VJcrRiu8=,tag:VLhTLBezNGH7A4pVu5Ljpw==,type:str]
            OPENAI_ADMIN_KEY: ENC[AES256_GCM,data:b9vyTkRsmxVgPYp5S9IEdMRpkPMRVB1j4xxcrDuDILU4S+1VugaLXd9h9dDPMi1CAxWvWbyVt3FXvdMUg2BEc86TDMXl5IP7zKTG8NxLNALh9gBZajZE9Iq6etAhI4tL0wJjF8vDFDgBkKbmPcTx90eQFieCF5rC+JzkxtxuLT4uxHUZZA==,iv:ZpybPC1P+pE8ZEc8sK2zq46CABMrgOY5y8zEqjfCU8o=,tag:BXHMCizOJQgkt8fjMq9PgQ==,type:str]
        - name: ENC[AES256_GCM,data:qmcfrgjdLXjK9/E=,iv:sdrC52NZYvWjBfjuiGWzVd2DM84Qem8yxYPlj0M2Q8s=,tag:8G5aEt2UeXewwljRUWXKjw==,type:str]
          stringData:
            AGENT_EMAIL_FROM: ENC[AES256_GCM,data:/YmCKUq83WzXpEm524Oynoips0JPSf94p0Kk,iv:LfjUYiL0oGHkN5HrIKimy+vyK6qeNkcn7/ll0Yi7FWs=,tag:D653jWpyMBw+q/QG0NLedg==,type:str]
            AGENT_ONBOARDING_REVIEW_EMAIL: ENC[AES256_GCM,data:5aWU3s66anHZ4ps7YWz+ijVE5YJ57j4=,iv:qlmzx1grSzvhnsyiuRBe8ScnK51qNXj5C2jBPXFYIcY=,tag:Y7JZ1yfyXD2RoJMxgY/Ozg==,type:str]
            AGENT_ONBOARDING_VERIFICATION_CODE_SECRET: ENC[AES256_GCM,data:udoADfpa+HJPw33JjcZ3rjs6rUBo5hi7kVJMYnBM1pXOCA1ykeoiepL0jEGAbDk7CH7bxOflyGdSMH0X7dTcPQ==,iv:yC03U4Nk7PURS8WraZfEyM8IGVcj8brAZOcne37PP+k=,tag:SeemxqamEhSGBSUnPi6tvw==,type:str]
        - name: ENC[AES256_GCM,data:FcOjyKZlR6yjB+C2PbYgXRUk,iv:1La9x+0Vtk6yr+3fPENvoD2CkvLa2mCWdLQ33AnF8Ww=,tag:moQdMXz18oCGXfv50uj6Sw==,type:str]
          stringData:
            ACCESS_KEY_ID: ENC[AES256_GCM,data:4JSApZwyIWDncon6s5jo2VyOT30=,iv:O3oyTV0JMuJ/UTailogKUdPDs1viANOaiTul1B/lWFc=,tag:oFSSD12XliO3XfXyre+fag==,type:str]
            ACCESS_SECRET_KEY: ENC[AES256_GCM,data:wmVEoJm9Sgp87vdx/dFhQlS4mrTrJskjNSkyuFd0sc+HBoikxc7f/w==,iv:IsVWsFCuwFtitM5eWez/67hXZov/ZZHjD7XlE704590=,tag:kaJk1IFR2XtjU1abS7tfXA==,type:str]
        - name: ENC[AES256_GCM,data:tW4kaxCu2srR,iv:wlaZGrMO3EEDQMx1aCrK6lO/yuqpIGkKHuZ5ny5Y9V0=,tag:Gser/QrkOOieY+DBK4Y7HA==,type:str]
          type: ENC[AES256_GCM,data:XWX692flH/3PClkDPYnWjAg6kdMPlkIUErW5TRQi,iv:pq5C/F0ie9r/4PSga8Hj9YzxOjWIvZgY8tTopQJh2WA=,tag:iqq44NYfR1CnjWciOWC/ZA==,type:str]
          stringData:
            .dockerconfigjson: ENC[AES256_GCM,data:nCbPU5A23mN3iSj0yLEGRMeFS3pjlSIqySKJz016m0gkl4o2cd6ro6BNxB6uobFKWZYObQDMvpcHRAmPQzOIR2cx4WSbSwm2beH5JZELXmVsfVXTtJkjxSeyV4bMheG/uRo1W+TnThRmtHuaeT0ZuCxZOjOlP15KD76H5ivhHeE65jDBv27x1c1pTpPVQo23YOCFTogjr8OCieeVl8eQ2v3iZnkBsukMoBoZJQZYUU+OJQ==,iv:jf5KzqNX+e5DCEUG7i4LhHPeBuZygZ4jPvBy3Wun3Q8=,tag:ZuG0w/mtTqtMQu3PhhzWrg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSbG1wZVl6K0EwUWwrVWJm
            VXRISTI4VlRHTmRnSnBOT1pQTXRSZGp1SEVrCk52Z0l0dmI4d2VjQncyWVF1ZDlo
            cW9tN2pBQ0p0eEh3b2lZc0hGNmNsN3cKLS0tIENBTHpGVCtCQ1RLc1VYaDE2M3RU
            N2RwblJDZ3prYUYzc1V4MU0wQjJsb1UKC06ZTyfiq/FuKRyCyiKy9OeZ6RXABrQy
            5Y4zXDR1bwWWYynGRq6z6WiNWr9pIhORvHYQGB3qecGV+VFGkQnHOg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14vn3sglty83cq3rtkzw0udlh3dak768daneupwxdqafgnewrhcsq9zawc6
    encrypted_suffix: Templates
    lastmodified: "2026-09-17T17:11:20Z"
    mac: ENC[AES256_GCM,data:tDj3cVWdNkfNdRQrZjg1chgRlKV1QdzlQvK2SWR58rC2NZUq8d8ESI1kVflUoEbPBFG3hZff+dArSN4R7yCFX6capWpFa/+CBIVT8IMKzcBOYBgoTIkCrznf/4bQQHdSQTQQnOIgJnxeyE2Q0bdPNqLWyTYx5DQcrPfF60GiCME=,iv:mtPSB8Kza1o2KJInEcWrE270+ol4TnLIDZJZ2TkdSBk=,tag:FhaQ6ljt8A/26LzhUNgzuQ==,type:str]
    version: 3.13.3
---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: cloudflare-dns
    namespace: cert-manager
    annotations:
        argocd.argoproj.io/sync-wave: "4"
spec:
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:/YEszb+/poVnzL8Ah23hnFs1AhQ=,iv:YJTKPoSQwzE3Ufr03ie7mf9dycom3fH8GWM4gSlMSQo=,tag:iXJYE0sghTkXlvK4dJs7OA==,type:str]
          stringData:
            api-token: ENC[AES256_GCM,data:j1Q2V29/Spbs5z7cZAiDi3AzBgqaxYR1fQ9N8o9VgViYUH3WPthH3vT3VQtHIhztEEwKsEA=,iv:xVuTa2eNGtVarEHQLq9Dj0v21f6Vt74AXIGT0LDUFeU=,tag:x2sGnyRd/X/h+MfgNgQkvw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSbG1wZVl6K0EwUWwrVWJm
            VXRISTI4VlRHTmRnSnBOT1pQTXRSZGp1SEVrCk52Z0l0dmI4d2VjQncyWVF1ZDlo
            cW9tN2pBQ0p0eEh3b2lZc0hGNmNsN3cKLS0tIENBTHpGVCtCQ1RLc1VYaDE2M3RU
            N2RwblJDZ3prYUYzc1V4MU0wQjJsb1UKC06ZTyfiq/FuKRyCyiKy9OeZ6RXABrQy
            5Y4zXDR1bwWWYynGRq6z6WiNWr9pIhORvHYQGB3qecGV+VFGkQnHOg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14vn3sglty83cq3rtkzw0udlh3dak768daneupwxdqafgnewrhcsq9zawc6
    encrypted_suffix: Templates
    lastmodified: "2026-09-17T17:11:20Z"
    mac: ENC[AES256_GCM,data:tDj3cVWdNkfNdRQrZjg1chgRlKV1QdzlQvK2SWR58rC2NZUq8d8ESI1kVflUoEbPBFG3hZff+dArSN4R7yCFX6capWpFa/+CBIVT8IMKzcBOYBgoTIkCrznf/4bQQHdSQTQQnOIgJnxeyE2Q0bdPNqLWyTYx5DQcrPfF60GiCME=,iv:mtPSB8Kza1o2KJInEcWrE270+ol4TnLIDZJZ2TkdSBk=,tag:FhaQ6ljt8A/26LzhUNgzuQ==,type:str]
    version: 3.13.3
