apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: customer-service-production
    namespace: customer-service-production
    annotations:
        argocd.argoproj.io/sync-wave: "15"
spec:
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:iFwKSmTphQU=,iv:G6CeLNJNxp/ZwAXFwhg2hzTF/AvXZcEq9IxfTIHqIJw=,tag:Lu1679CHxBt2hHGOHE4qEg==,type:str]
          stringData:
            OPENAI_API_KEY: ENC[AES256_GCM,data:X7C5MwZaEervq+iuktO+YkhxtN/7/v6qLPRj8yqKfCFh2PBdaEMINNnSW4WwHR8Ee5Y/qPz4jfmWQ4RR7k6+ui8PdjXGMptBQWuEAohBre0YLhG0T1nWFo2DJgTQ/sDyb6Sn0S5ZAk1xEKob8qqqDUTElMmfkNeWAPUOmKNHYxDGDH42vUhc/4rCiuqqFPgtpxHwl9kBb15LOn2uXeKo8wj8lMU=,iv:3p8rNxzXk6XImCMpTCrKpVbJcRJPvlMdYOEzCBx+EP4=,tag:31rf6PGWvpqCqM4nNdayFw==,type:str]
            LANGSMITH_API_KEY: ENC[AES256_GCM,data:6fH0gXT009LqzbAO8tHOXBGhyDfD0M+RRx4BHl5poeE303M0wQNC+bLGa76o7XueeK8S,iv:aHZHw9b0gacUqe6+l/2rmygoZdVC5SiWqCmqHiHuiFY=,tag:uqPRv2TuhhKWxvB3/xEkyQ==,type:str]
            LANGSMITH_WORKSPACE_ID: ENC[AES256_GCM,data:zW3LlcBqGCu81CRFlvQz9eHzrmP12O6rn7wvTO+5JsTbdM/w,iv:LLdTdLkMJROaU4i/c6otODNYGwcKGHFXORCKyk7k9No=,tag:EFwRQOn08/9bHDF8xWzspQ==,type:str]
            RESEND_API_KEY: ENC[AES256_GCM,data:b6qme6M+i3sW8SeVf1o/EuLjBBaEuzGahCrDILPTJRZobnU6,iv:F46w5ZH799I6fxsHafbkRbYZysSnRhWk6Vuht5zbyVE=,tag:2Coy4Yi5rH0lnuhh3F+n5w==,type:str]
            PLATFORM_TAVILY_API_KEY: ENC[AES256_GCM,data:dRsDppRsapZgdtGC21VhyECtAhTzZYLI9LwaL7ta3uP3pkSBmGMTrHk3+2pVHYPuE2LzbjlPVTcKMA==,iv:ddPWILztFU2Je4q/qWbbVgkVH0AlMCfQzulWfYNBteU=,tag:GzTjqBXtaTOCNrHDT3Tfag==,type:str]
            OPENAI_ADMIN_KEY: ENC[AES256_GCM,data:1BM3UP8/VZR0BjxNm/MSV19kImdArsI87DgsuLu4eqwtVsqzae+/yFaiO3wGI/Re2fW9+hs3lWZ+LKxZPERXN1I1Co73+JRwMQ4IbV0qHbbmrYlFSFaZwQm0ouc1h39Bjl9Fzcn7lwM/5IbdhX7BMzgW5Bo6i0KVj8u4nTqiq3hLgnYHPg==,iv:pGugTEa2dBAjd/Mfblv4iNsDwcAv7tMvYgxuUX3zO2U=,tag:mJbvsZQo5LViGe3lLkdOfQ==,type:str]
        - name: ENC[AES256_GCM,data:u8eXcDclmEC4IJA=,iv:JMjraCzHDzcI22FAKgggOPsPcDEjQuQ1rxJt54F5JUI=,tag:92/e9NdCYmmxMZ1ph0US9A==,type:str]
          stringData:
            AGENT_EMAIL_FROM: ENC[AES256_GCM,data:tL93xpBQT6GBPrbn9wMdCVaViyVym12Lk3Dg,iv:M7ZFeUA4DeNglIMnW61VVEgAMQewRzBstm7YILOTH+Y=,tag:5bLyOyBe8aJnGStzmJVH3w==,type:str]
            AGENT_ONBOARDING_REVIEW_EMAIL: ENC[AES256_GCM,data:16TMJHpPqMOmUOYkKo3CcKa5gvx1tZU=,iv:TX/03zJo023aqxFE2/jjtVPn7D7wmUcH6gsu+aSLoMs=,tag:FalmZf1gQsquecFB9uCUBA==,type:str]
        - name: ENC[AES256_GCM,data:WOgyPfVbaZJR/tiVW+4IeZoe,iv:NphLae9fKHWw2bcxGoSwi/hiCFOXN6g8VQIljO1KnYY=,tag:7L/kXsGMcNzjMYvxQ1sCsw==,type:str]
          stringData:
            ACCESS_KEY_ID: ENC[AES256_GCM,data:njlhkOpkzWTjqgAYv6SKB/LuQWo=,iv:DzKJPcwvhFyM6Z9rtLAgH5vSqw3sKmkjULfpXcNxqqo=,tag:JqJfMUmKeMfpsK+wd7yGyw==,type:str]
            ACCESS_SECRET_KEY: ENC[AES256_GCM,data:2LZJrdXF6th+m0IA/kEKoRRNj1JrUWo806i5hJ4n0G5WIMjdw3cyqw==,iv:2dkQmdbkvBBNwj5OTMoISjHvvpgUcov3zC4evUeBkiI=,tag:B/qMySurLiUt7dIUbKLQkQ==,type:str]
        - name: ENC[AES256_GCM,data:0jkVoDdteMyy,iv:EgQ+600jOEfOb8boPu1IBsVdC/7Ca6AXoG0EbR5Ugug=,tag:vNz8+frIbytmJw//f1gwow==,type:str]
          type: ENC[AES256_GCM,data:809LXwB54JdlSKvMQe7XesRdkQx4SQwzCKZz2+ya,iv:IqubqrdKCUNVen8k8igvZ1sx2KeBwVg0r48LGA9HN84=,tag:meU8hqjuebnKcHSx4b1YhA==,type:str]
          stringData:
            .dockerconfigjson: ENC[AES256_GCM,data:J9qTlJ1r9jrllSvWfWIXf2Y1bLDVvcvYcFq/8iCHmJFbWKV1r2INw425qjuwqYS13+5BR3welB77QDfYXOS6y9v9lFXmbzrU2YwJ63n0T7vwU9CC1kfLFfHIi1gq4XoFVuGbyywGyW1BluUeaWzWq7cXAwQDOhugwm7gQjIsJH26+mNE/WqUDN41zRZhebkdkHGDG7J6G04NQt60tDEGkky0z27Vd0ruQ074F1rlAR4bgg==,iv:i7fWmeWlyVEzTo3K1uKAaBNNCJ3QiskVqY9mWYmWwK4=,tag:sZ4BlSSWbJi+OAJ3+/Z/0g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWQlVha0srMnpzemU5bDNC
            N0FIREgvckRBZUYwTlJQVzVJTUZGclBObVZNCndGdURZcEh1NmVHdHBVbW5iQ2po
            aFpDTTBEM09rdms4TmhLU09QQmlzT3MKLS0tIC9ONXJBbldueXM5UUw0dnZnWURK
            bkZXNG50MFFLN2VhT3ZLbWF0WjB2aDAKHEXnXphRU/hzkQB5EaSgjFLoz/1eW/od
            x3zM3x5bEV01OesD8y9I7QtydZShaTPrivfw8QHOLKRYGa8nCR8S9A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14vn3sglty83cq3rtkzw0udlh3dak768daneupwxdqafgnewrhcsq9zawc6
    encrypted_suffix: Templates
    lastmodified: "2026-09-16T15:53:30Z"
    mac: ENC[AES256_GCM,data:sREFaTD7HZM48yttyO+QF8/dtWlNj+0FFAHURDEeQ6YYcT+d50iUkWuCFzCT9vaL+OR6csE0ZnvvRFHHodqZY+1epjoAl+I49QN+2lkMYXKfMwm6kUlc26NMUhR9UM6FnLwXXgZ0zk+KO8SE++gBrCN95FZV9yRcRNgm5HGgo5k=,iv:EtNy1yqweA9+cZNX0rl573kxlt9lgvpqQSQnE/qaXH4=,tag:fxF3sL8GnXcTvaIGovHh8A==,type:str]
    version: 3.13.3
---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: cloudflare-dns
    namespace: cert-manager
    annotations:
        argocd.argoproj.io/sync-wave: "4"
spec:
    suspend: false
    secretTemplates:
        - name: ENC[AES256_GCM,data:dh+zHDtSwcLIbZUsmkN54YL7tSY=,iv:fY/5mvw8oRLVRjkSJG3lyMZmA6rs2qax9mUQ3cMF/IE=,tag:LL3kg5rJcHKBtcUALBN2tw==,type:str]
          stringData:
            api-token: ENC[AES256_GCM,data:ZeNKpcyCnZkwoPZ0XgGkBpc02t27Q0PFXP4i6n9xaBYhVmgSTk7XiHd4T3/kFY+xjmuncO4=,iv:WsdEFowBay9IMTulqx1HXaix0S8EiiaxA4YCihJBZko=,tag:VFyK7BeLaPupWF02qSwxUQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWQlVha0srMnpzemU5bDNC
            N0FIREgvckRBZUYwTlJQVzVJTUZGclBObVZNCndGdURZcEh1NmVHdHBVbW5iQ2po
            aFpDTTBEM09rdms4TmhLU09QQmlzT3MKLS0tIC9ONXJBbldueXM5UUw0dnZnWURK
            bkZXNG50MFFLN2VhT3ZLbWF0WjB2aDAKHEXnXphRU/hzkQB5EaSgjFLoz/1eW/od
            x3zM3x5bEV01OesD8y9I7QtydZShaTPrivfw8QHOLKRYGa8nCR8S9A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14vn3sglty83cq3rtkzw0udlh3dak768daneupwxdqafgnewrhcsq9zawc6
    encrypted_suffix: Templates
    lastmodified: "2026-09-16T15:53:30Z"
    mac: ENC[AES256_GCM,data:sREFaTD7HZM48yttyO+QF8/dtWlNj+0FFAHURDEeQ6YYcT+d50iUkWuCFzCT9vaL+OR6csE0ZnvvRFHHodqZY+1epjoAl+I49QN+2lkMYXKfMwm6kUlc26NMUhR9UM6FnLwXXgZ0zk+KO8SE++gBrCN95FZV9yRcRNgm5HGgo5k=,iv:EtNy1yqweA9+cZNX0rl573kxlt9lgvpqQSQnE/qaXH4=,tag:fxF3sL8GnXcTvaIGovHh8A==,type:str]
    version: 3.13.3
